### ISSUE TITLE
炼成模式下，有天邪鬼职业的玩家不含有村侧职业也会和村侧一同胜利

### ISSUE THREAD

**Issue by chanssi** [Sunev/jinrou#106]
**简述bug**
天邪鬼职业的玩家在炼成模式下即使不含有村侧职业也会和村侧一起胜利

**出现bug的房间地址**
https://www.werewolf.com.cn/room/87805

**出现bug的玩家昵称**
刘小别

**出现bug的时间**
结算时

**预期行为**
天邪鬼不能胜利

**截屏**
<img src="https://i.loli.net/2019/07/05/5d1f1739b70c026865.jpg" alt="Screenshot_20190705-172344.jpg" title="Screenshot_20190705-172344.jpg" /> 
**更多内容**
是天邪鬼x狼侧职业的时候也会和村侧一同胜利，但是找不到房号了（下锅太多

**Comment by Sunev** [comment]
由 https://github.com/uhyo/jinrou/pull/584 修复
