### ISSUE TITLE
加入有主题的匿名房间时，仍提示要输入昵称及头像

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#110]
**简述bug**
加入有主题的匿名房间时，仍提示要输入昵称及头像

**出现bug的房间地址**
https://www.werewolf.com.cn/room/90616

**出现bug的玩家昵称**
夜莺（Default）

**出现bug的时间**
第一天夜里加入时

**预期行为**
不出现昵称和头像的输入框

**截屏**
![无标题](https://user-images.githubusercontent.com/29174788/62451160-4910d100-b7a0-11e9-819a-179bbda337b4.png)

**更多内容**
把出现bug的号永封了吧求你了字母！要不然我真的戒不掉人狼了啊啊啊啊啊啊啊啊啊啊啊

**Comment by Sunev** [comment]
你的意思是叫我封掉你的号？

**Comment by StarlightA** [comment]
是的因为我想戒掉人狼

**Comment by Sunev** [comment]
不能复现此bug
