### ISSUE TITLE
复仇者在死亡后选择射击目标前，修改遗言会正常保存

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#112]
**简述bug**
当复仇者（推测狩猎者同）死亡而正在选择射击目标时，可以正常保存遗言，而不是像一般情况下被提示“你已经死了”

**出现bug的房间地址**
N/a

**出现bug的玩家昵称**
N/a

**出现bug的时间**
N/a

**预期行为**
保存遗言时提示“你已经死了”

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
你用最后的力气举起了猎枪，没有力气说遗言了，谢谢

**Comment by YagamiMirai** [comment]
> 你用最后的力气举起了猎枪，没有力气说遗言了，谢谢

所以说保存的时候应该要提示你已经死了啊。。但是没提示啊。。。还是可以保存的啊。。。所以是bug啊。。。
