### ISSUE TITLE
替身是圣诞老人的情况下，作为驯鹿的玩家没有游戏体验

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#126]
**简述bug**
请概要地描述一下bug的情况。
替身是圣诞老人，玩家是驯鹿，第一天就死了。
虽然从逻辑来讲没问题但是会影响玩家的游戏体验。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/99118

**出现bug的玩家昵称**
驯鹿=【真香】曼荼荼大人

**出现bug的时间**
第二天的白天到来时

**预期行为**
不然替身有安全性的时候拿不到圣诞老人？

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
另外你公告的日期是认真的吗？11月24日-25日？

**Comment by Sunev** [comment]
已修复
