### ISSUE TITLE
（代天之声提交）巫女技能效果意外延长

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#127]
**简述bug**
请概要地描述一下bug的情况。
巫女D2夜间使用技能并抵抗了袭击，在D4日间又抵抗了处刑。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/99674

**出现bug的玩家昵称**
黑猩猩的义妹

**出现bug的时间**
使用技能：D2夜 
抵抗袭击：D3天亮 
抵抗处刑：D4投票

**预期行为**
请简单描述一下你认为此处在没有bug的情况下应该是什么样子。
不应该延伸到D4

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。
怀疑和小丑的离开有关

**Comment by Sunev** [comment]
初步认为与丑时之女有关

**Comment by Sunev** [comment]
由 54f5ae407a2592cf253b6f1e1b0a72d9d0dbb8b7 修复
