### ISSUE TITLE
出现第一夜结束游戏即告结束情况

### ISSUE THREAD

**Issue by zhengmingchu** [Sunev/jinrou#130]
敬爱的开发团队：
       今晚与群友在贵站玩游戏期间遇到了一些异常的情况，恐是系统bug所致，现叙述情况如下：
**简述bug**
三个房间都是第一夜结束之后游戏直接结束，突然胜利（如第一局全员存活却显示恋人胜利，第二局村人和狼均在场却显示妖狐胜利，第三局只死了替身君其余人全部存活却显示恋人胜利）

**出现bug的房间地址**
https://www.werewolf.com.cn/room/107700
https://www.werewolf.com.cn/room/107695
https://www.werewolf.com.cn/room/107684

**出现bug的玩家昵称**
郑铭初，RachelRachel，∑，嘻嘻等，这三个房间的全部玩家
**出现bug的时间**
第二天白天

**预期行为**
游戏继续直到出现正常的结果

**截屏**
![image](https://user-images.githubusercontent.com/61836104/75990477-e945f880-5f2f-11ea-881c-838c84d59e6e.png)

![image](https://user-images.githubusercontent.com/61836104/75990802-607b8c80-5f30-11ea-96c4-7ce63117a8f8.png)

**更多内容**
无

盼能尽快解决此等问题，不胜感激，此致
敬礼 
                                                                                                    郑铭初

**Comment by StarlightA** [comment]
#107684 炼成人狼中人狼系×人狼系算作两头狼，此局共有3狼，1狐，3村人，达到妖狐胜利条件，但因为有恋人存在且未开启“只有恋人生存恋人阵营才会获胜”的设置，所以判定为恋人胜利。而day1没有结算是因为day有2狼、1狐、4村人（模仿者尚未模仿），未达到任何阵营胜利条件。而技能是在第二天白天才判定的，所以第二天白天恋人直接胜利。
#107695 和上一局基本相同，结算时有2狼，1狐，2村人，达到妖狐胜利条件，所以妖狐获胜。
#107700 也是一样的，结算时有2狼，1狐，2村人，达到妖狐胜利条件，但因为有恋人存在且未开启“只有恋人生存恋人阵营才会获胜”的设置，被判定为恋人胜利。

**Comment by Gennadiyev** [comment]
个人意见，但是这是游戏特色。您可以调高游戏安全性来尽可能规避这些情况。
