### ISSUE TITLE
EL，恋侧德古拉、未吸血的魔女、吸过血的丘比特，处刑第4人后结算，鬼胜，恋侧3人败

### ISSUE THREAD

**Issue by 600g** [Sunev/jinrou#131]
**简述bug**
恋侧德古拉、未吸血的魔女、吸过血的丘比特，处刑第4人后结算，鬼胜，恋侧3人败

**出现bug的房间地址**
https://www.werewolf.com.cn/room/111333

**出现bug的玩家昵称**
相对的正义

**出现bug的时间**
第四天处刑后

**预期行为**
恋侧胜利

**截屏**
![截图20200325134917](https://user-images.githubusercontent.com/41325798/77506830-cc9f3f80-6ea1-11ea-800d-afe64900bd01.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by KokoneMirano** [comment]
![eb9b3ca89fa1cff3ccb3fdcb502415e](https://user-images.githubusercontent.com/108578695/179720312-6959aa3f-dff5-4972-b598-d656d1bda6e5.png)
