### ISSUE TITLE
醉鬼的职业描述

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#144]
**简述bug**
醉鬼在炼成人狼的里面职业描述不正确。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/148120

**出现bug的玩家昵称**
【喝茶联盟】???

**出现bug的时间**
该局游戏全部

**预期行为**
你的身份是 村人×村人（村人的详细・村人的详细）

**截屏**
https://sm.ms/image/GOhgDbr1tQEF2sv
https://sm.ms/image/dG4AkED2HyBVSZY
图片传不上来
第一张是正常职业的时候
第二张是发生bug的醉鬼职业的时候

**更多内容**

**Comment by Gennadiyev** [comment]
是时候打上 Big bug wont fix 的 Tag 了吗（bu

**Comment by Sunev** [comment]
图片看不到，描述的问题明白了，你可以去和uhyo提issue，我最近工作比较忙基本放任

**Comment by YagamiMirai** [comment]
结果有人提交给U大吗 不然我提交去好了…
