### ISSUE TITLE
bug报告

### ISSUE THREAD

**Issue by kikuchi1** [Sunev/jinrou#158]
**简述bug**
请概要地描述一下bug的情况。
两人两个账号在同一个地址、并且连了同一个WiFi进入同一房间时，会显示「禁止多开」。我和我的朋友在一起玩的时候总会有一方在加入时显示「禁止多开。」这让人很困扰，希望可以多加完善关于「多开」的判别。

**出现bug的房间地址**
/

**出现bug的玩家昵称**
池

**出现bug的时间**
进入房间时。

**预期行为**
因为是两人两个账号，不存在多开现象。所以不应该显示「禁止多开」，而是两人都能进入房间才对。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
受技术手段限制，同一IP下的所有账号被视为同一用户操作，确有误伤同一WiFi在线的情况，但是现阶段没有方案能够证实同一WiFi下的多个账号系不同用户操作，无法解决此问题。

作为替代方案，可以有一方使用4G网络，或者使用翻墙工具改变出口IP规避此问题。
