### ISSUE TITLE
（代AK提交）举报利敌行为

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#159]
**简述bug**
请概要地描述一下bug的情况。
例如：「替身君」猝死了。

**出现bug的房间地址**
www.werewolf.com.cn/room/169957

**出现bug的玩家昵称**
由Akioi举报王五子（独裁）

**出现bug的时间**
D2白日利敌行为

**预期行为**
独裁者不该在非EL锅内盲目释放技能

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。
仅为代提交。

**Comment by Sunev** [comment]
独裁跳劈是游戏的一部分
