### ISSUE TITLE
Endless模式下 主播死亡并转生后，观众依旧能看到其释放技能时的提示

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#160]
**简述bug**
请概要地描述一下bug的情况。
在endless模式下，当一名主播还有存活的观众时死亡并转生为有技能提示的职业时，释放技能的提示依旧会展示给观众。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/170175

**出现bug的玩家昵称**
主播：鱼家小店的偶像鱼儿大人（作为弗兰肯斯坦的怪物）
观众：【香喷喷】曼荼荼大人

**出现bug的时间**
第4天的夜晚

**预期行为**
不该展示给原观众。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。
不确定是否和死亡后立刻转生这一点有关。

**Comment by Sunev** [comment]
和死亡后转生有关，和立不立刻无关
