### ISSUE TITLE
Endless频繁出现投票窗口消失

### ISSUE THREAD

**Issue by sarayana** [Sunev/jinrou#163]
**简述bug**
Endless，安全性中，频繁出现投票的候选人消失，无法投票，卡在瞄准的00:00等事件。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/173094
https://www.werewolf.com.cn/room/173091

**出现bug的玩家昵称**
全员

**出现bug的时间**
第二天白天

**预期行为**
正常进行游戏。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by YagamiMirai** [comment]
bug房间记录：（由Akioi整理）
172598
172717
172719
172727（由GM调整时间规避成功）
172738
172743（由GM调整时间规避，但依旧不显示投票框导致全员猝死）
173049
173082
173091
173094

日服bug房间：
https://jinrou.uhyohyo.net/room/201127
https://jinrou.uhyohyo.net/room/201288

均为在endless模式下，表现为天亮后计时器卡在上一个计时的0:00上（夜/犹豫/瞄准等）。

**Comment by sarayana** [comment]
您好，我已收到您的来信。
