### ISSUE TITLE
（代提交）举报多开行为

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#165]
**简述bug**
请概要地描述一下bug的情况。
例如：「替身君」猝死了。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/173407
https://www.werewolf.com.cn/room/173417

**出现bug的玩家昵称**
多开的玩家ID=1102 
昵称 海盗🏴☠️/赌博

**出现bug的时间**
21:57:10：173407房间开始，此时该玩家处于此房间游玩中。
22:21:43：该玩家加入173417房间，此时该玩家于173407尚未死亡。
22:29:51：173417房间开始，该玩家同时进行双房间的游玩。
22:33:19：该玩家于173417房间被处刑而死。
22:37:51：173417房间结束。
22:50:02：该玩家于173407房间被袭击而死。
22:53:09：173407房间结束。
即：该玩家在173417房间中的所有时间，均处于其加入173407房间正常进行且未死亡的状态。

**预期行为**
同时加入多个游戏是服务器所禁止的行为。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
已处理，封禁24个月
