### ISSUE TITLE
Bug报告

### ISSUE THREAD

**Issue by Myelsen** [Sunev/jinrou#174]
**简述bug**
对战过程出现卡顿以至于在陈旧房间待了五天，且无法废弃

**出现bug的房间地址**
https://www.werewolf.com.cn/room/189535

**出现bug的玩家昵称**
圣空星王
菲利斯·尼克瑞斯
鬼狐天冲
雷伊
京弥
光族亲王
安迷修
金
星际财团会长
秋

**出现bug的时间**
第2天的夜晚

**预期行为**
应该赢来第3天的早晨吧（？

**截屏**
![image](https://user-images.githubusercontent.com/98511785/151304092-dadcc186-7ae5-47b6-9baa-3b689d1b2838.png)

**更多内容**
有人反映是可能会和影法师的作用有关

**Comment by Sunev** [comment]
自开服以来一直有此bug，一直是我手动清除，原因难觅，无从处理

**Comment by Myelsen** [comment]
> 自开服以来一直有此bug，一直是我手动清除，原因难觅，无从处理

最近又攒了三个这样的房间在陈旧里，麻烦您手动清除啦
