### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by yechuan-wink** [Sunev/jinrou#196]
895501**简述bug**
请概要地描述一下bug的情况。
例如：「替身君」猝死了。
开起房间时设置密码使用了中文，无法进入房间了
**出现bug的房间地址**
请于此处粘贴网址。
https://www.werewolf.com.cn/room/227872
**出现bug的玩家昵称**
请于此处粘贴玩家昵称或ID。
赞美愚者bot
**出现bug的时间**
例如：第一天夜里；第三天投票阶段等等
建立房间
**预期行为**
请简单描述一下你认为此处在没有bug的情况下应该是什么样子。
设置密码时禁止输入中文
**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by StarlightA** [comment]
设置密码时候可以输入中文和其他特殊符号是月下人狼特色

**Comment by yechuan-wink** [comment]
> 设置密码时可以输入中文和其他特殊符号是月下人狼色

但进入房间时无法输入中文密码，只能输入英文和数字以及符号

**Comment by StarlightA** [comment]
你可以复制粘贴
