### ISSUE TITLE
[代提交]发现一些账号被莫名封禁

### ISSUE THREAD

**Issue by chenpotatos** [Sunev/jinrou#203]
**简述bug**
账号莫名被封，大概是误封，如果可以也请解封，谢谢！

**出现bug的房间地址**
请于此处粘贴网址。

**出现bug的玩家昵称**
miku,230319,HL,andyxza,HI

**预期行为**
希望字母老师能解封下账号，谢谢了。这些都是我朋友，玩月下挺久了，号没了也挺可惜的。

**Comment by chenpotatos** [comment]
了解了下原因，应该是朋友间的恶作剧，登了另一个朋友的号。麻烦字母老师处理下，谢谢了。（鞠躬）

**Comment by Sunev** [comment]
刚看到，没几天了，保管好自己的账号吧
