### ISSUE TITLE
狼仆复仇者无法向替身狼开枪

### ISSUE THREAD

**Issue by 600g** [Sunev/jinrou#32]
**简述bug**
狼的仆从（复仇者）选定替身君（瞳狼）点击开枪后没有反应，重复操作数次后结果不变。瞄准时间结束后自动选择了其他目标。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/65939

**出现bug的玩家昵称**
相对的正义

**出现bug的时间**
第8天白天天亮

**预期行为**
复仇者可以选定替身君开枪。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
第7天夜晚，替身君通过为狼子复仇咬死了包括狼仆复仇者的两人。第八天天亮时，仅剩替身君和间谍二存活。选定替身君开枪后，虽然没有反应，但是可以重新选择目标。

**Comment by Sunev** [comment]
是没有弹出任何对话框，只是点击开枪后选择目标的菜单就又出来了是吗？
