### ISSUE TITLE
魔术师可以对刚转生的人使用复活术

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#33]
请概要地描述一下bug的情况。
魔术师可以对刚转生的人使用复活术。
**出现bug的房间地址**
https://www.werewolf.com.cn/room/66028
**出现bug的玩家昵称**
援交♡少女シャロ酱☑  宗泽
**出现bug的时间**
第三天夜里
**预期行为**
魔术师只能对死人使用技能
**截屏**
抱歉我不会上传图片……
**更多内容**
抱歉我不懂程序……

**Comment by Sunev** [comment]
。。。上报模板里的特殊符号你别删啊，那是排班用的
还有两个bug分开报，混在一起我看着费劲

**Comment by Sunev** [comment]
804a504 修复
