### ISSUE TITLE
拒绝复活然后转生的BUG

### ISSUE THREAD

**Issue by Jonser6** [Sunev/jinrou#34]
**简述bug**
请概要地描述一下bug的情况。
D3拒绝复活者D4复活

**出现bug的房间地址**
https://www.werewolf.com.cn/room/66062

**出现bug的玩家昵称**
相对的正义 ID：600g

**出现bug的时间**
D3夜间拒绝复活
D4被狼刀后立刻转生

**预期行为**
D4玩家被狼刀不转生

**截屏**
不知道咋在github插图片

**更多内容**

**Comment by Sunev** [comment]
f5c2a91 修复
