### ISSUE TITLE
反馈bug：阎魔无法看到天降背德者天亮时自尽的原因

### ISSUE THREAD

**Issue by zxcvbnm13246** [Sunev/jinrou#37]
**简述bug**
阎魔无法看到天降背德者天亮时自尽的原因，或者是阎魔职业描述错误。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/67189

**出现bug的玩家昵称**
昵称：tusizi

**出现bug的时间**
第二天天亮时。

**预期行为**
按照阎魔职业描述应该显示“伊庭宗一 的死因是 追随妖狐自尽”。

**截屏**
![tim 20180810214424](https://user-images.githubusercontent.com/42093500/43961230-ebf65280-9ce6-11e8-8a53-c69bad56c300.png)
![tim 20180810214432](https://user-images.githubusercontent.com/42093500/43961233-eef14300-9ce6-11e8-9ff4-7cd6305b531a.png)

**更多内容**
字母我拿着bug来兑奖啦——

**Comment by Sunev** [comment]
2a569c2 修复
