### ISSUE TITLE
匿名局结束后看不到皮下

### ISSUE THREAD

**Issue by Jonser6** [Sunev/jinrou#39]
**简述bug**
请概要地描述一下bug的情况。
匿名局点击角色名显示【这个玩家不存在】

**出现bug的房间地址**
https://www.werewolf.com.cn/room/67636

**出现bug的玩家昵称**
参与游戏的全体成员

**出现bug的时间**
游戏结束后
**预期行为**
可以看到皮下。

**更多内容**
昨天刚发现的问题，不知道是不是更新后的bug

**Comment by Sunev** [comment]
这个是昨晚准备第二次停机更新的时候发现有两个房间在跑，所以没弄完
现在已经解决了
