### ISSUE TITLE
在场上2+人狼的情况下，替身君抢刀

### ISSUE THREAD

**Issue by Jonser6** [Sunev/jinrou#43]
**简述bug**
请概要地描述一下bug的情况。
在场上2+人狼的情况下，替身君抢刀
**出现bug的房间地址**
https://www.werewolf.com.cn/room/69063

**出现bug的玩家昵称**
替身君

**出现bug的时间**
第二天夜里
**预期行为**
玩家选择刀人

**截屏**
不会插入图...

**Comment by Sunev** [comment]
于 00a0dca 已修复
