### ISSUE TITLE
女王死亡村人未追随

### ISSUE THREAD

**Issue by Jonser6** [Sunev/jinrou#44]
**简述bug**
请概要地描述一下bug的情况。
女王死亡村人未追随

**出现bug的房间地址**
https://www.werewolf.com.cn/room/69142

**出现bug的玩家昵称**
扑克脸路人男以及其他村人

**出现bug的时间**
第三天白天
**预期行为**
女王死后村人追随

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
![image](https://user-images.githubusercontent.com/12387091/48771356-29ae4280-ecfc-11e8-8c51-476482552364.png)
被催眠了，不是bug
