### ISSUE TITLE
怪诞狂热者 指定 拥有占卜套装的狼 变成了 占卜师。

### ISSUE THREAD

**Issue by Camiuuu** [Sunev/jinrou#47]
**简述bug**
怪诞狂热者 指定 拥有占卜套装的狼 变成了 占卜师。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/70358

**出现bug的玩家昵称**
“【反喝茶联盟】曼荼” “嫌味。”

**出现bug的时间**
第五天夜里

**预期行为**
怪诞狂热者 指定 拥有占卜套装的狼 变成了 人狼。

**截屏**
无

**更多内容**
无

**Comment by Sunev** [comment]
由 5c47c0b 修复
