### ISSUE TITLE
有人猝死后卡住

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#48]
**简述bug**
请概要地描述一下bug的情况。
夜里有人猝死后游戏卡住

**出现bug的房间地址**
https://www.werewolf.com.cn/room/70651

**出现bug的玩家昵称**
akioi 

**出现bug的时间**
第二天夜晚

**预期行为**
猝死后结算或游戏继续

**Comment by YagamiMirai** [comment]
另：在猝死卡住1天18小时13分40秒后系统给出了新的猝死提示。

**Comment by Sunev** [comment]
还计算一下时间，你好闲哦！

第二次猝死是因为服务器重启过，房间的实例重新初始化了

**Comment by YagamiMirai** [comment]
本来想思考一下会不会是什么计算上限来着（2147483647之类的）

以及为什么第二次会比第一次多猝死一个人呢？

**Comment by Sunev** [comment]
因为第二次猝死的时候所有人都没在操作，所以多了一个天之声（法医）猝死

**Comment by Sunev** [comment]
入夜的时候 akioi 还活着，替身君 就没有袭击
夜间结束的时候，场上有2狼，替身君 和 akioi 都没有袭击
夜间犹豫结束的时候，akioi 猝死，替身君 因为 不需要袭击就没有猝死

结果有1狼生存，却没有袭击目标，就卡死掉了

**Comment by YagamiMirai** [comment]
所以为了不让替身君抢刀 干脆替身君就没有默认袭击能力吗…迷茫（说起来替身不应该一起猝死掉吗

说起来这会不会影响孤独的狼？如果有一孤独的狼和一别的狼存活 孤独的狼不能选择袭击目标 然后另一个狼猝死的话 孤独是会一起猝死吗？还是也会卡住？亦或者可以选择并袭击目标？
