### ISSUE TITLE
被炸弹炸死时显示死亡原因是“未知原因”

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#49]
**简述bug**
请概要地描述一下bug的情况。
被炸弹炸死时显示死亡原因是“未知原因”

**出现bug的房间地址**
https://www.werewolf.com.cn/room/70672

**出现bug的玩家昵称**
便携狸猫 

**出现bug的时间**
Day2投票后入夜前

**预期行为**
死亡原因 是 炸弹或者之类的？

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 9bd5615 修复

**Comment by YagamiMirai** [comment]
> 由 [9bd5615](https://github.com/Sunev/jinrou/commit/9bd56150a1a1f8c4946d7d3b58206ea760210c80) 修复

okk 另一个呢？
