### ISSUE TITLE
Endless下粉丝转生后，偶像依旧能获得村侧信息。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#53]
**简述bug**
请概要地描述一下bug的情况。
在Endless模式下，粉丝死亡并转生后，偶像依然会获得【根据 ○○ 的敏锐观察，现在村人阵营的人数有 ○ 人。】的提示，也依然会在第四夜获得新的粉丝。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/70990

**出现bug的玩家昵称**
偶像：路德 
粉丝：deemo

**出现bug的时间**
转生时间为第四天早上

**预期行为**
转生后判为粉丝死亡。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 2ee639f42c712fea16065cfb974b7083470a4a28 修复
