### ISSUE TITLE
ios手机默认浏览器（safari）中，职业信息覆盖于系统提示框之上

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#54]
**简述bug**
请概要地描述一下bug的情况。
ios手机默认浏览器（safari）中，阵营职业信息覆盖于系统提示框（例如拒绝复活、投票封禁等）之上，其它浏览器暂未测试。

**出现bug的房间地址**
N/A

**出现bug的玩家昵称**
N/A

**出现bug的时间**
N/A

**预期行为**
提示框位于最上层，类似电脑网页端

**截屏**
https://s1.ax2x.com/2018/12/22/5WBoaE.jpg

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
safari的版本号是多少？
应该可以在“关于”里面查到

**Comment by YagamiMirai** [comment]
没能找到。。。系统版本是11.4.1

**Comment by Sunev** [comment]
由 cfb0c782 修正
