### ISSUE TITLE
（代天之声提交）炼成模式下 阎魔无法看到被炸弹炸死的死因

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#56]
**简述bug**
请概要地描述一下bug的情况。
炼成模式下 阎魔无法看到被炸弹炸死的死因（并不显示）。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/71515

**出现bug的玩家昵称**
天之声

**出现bug的时间**
第二天天亮

**预期行为**
xxxx 的死因是 炸弹。

**截屏**
我也想但是天之声没有提交给我截图…

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 b59f82592621c7380e9841ab9319c36b6c87075e 变更译文为“陷阱”
另注，日服并没有“炸弹”这个死亡原因，被炸弹炸死后，阎魔是显示“死于陷阱”的
在灵界的详细死亡原因则会显示“死于炸弹”
