### ISSUE TITLE
探亲者的离开在灵界显示死因为”间谍失踪。“

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#60]
**简述bug**
请概要地描述一下bug的情况。
第四天早上探亲者离开游戏时，灵界显示的死因为【XXX 的死因是 间谍失踪。】

**出现bug的房间地址**
https://www.werewolf.com.cn/room/71671

**出现bug的玩家昵称**
【爱喝茶联盟】曼茶 （这个**也**是我的小号）

**出现bug的时间**
第四天早上

**预期行为**
【XXX 的死因是 探亲者的离开。】之类的？

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 b59f82592621c7380e9841ab9319c36b6c87075e 变更译文为“行踪不明”
