### ISSUE TITLE
在游戏开始的瞬间退出游戏导致5人就开始游戏。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#62]
**简述bug**
请概要地描述一下bug的情况。
在游戏开始的瞬间退出了游戏导致游戏开始时包括替身在内只有5人。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/71879

**出现bug的玩家昵称**
akioi 

**出现bug的时间**
游戏开始时

**预期行为**
不能在这个时间点退出游戏

**截屏**
![image](https://user-images.githubusercontent.com/44828559/50808803-3c77e780-133b-11e9-85c2-a521ae9daea1.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
做不到，再见

**Comment by Camiuuu** [comment]
做不到笑死
