### ISSUE TITLE
提议修改：二重身的职业描述【Not bug】

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#63]
二重身的职业描述中，有“最初属于村人侧”这样的语句。但二重身不进行变化是无法胜利的，这句话似乎不合逻辑。

（相对的，另一个有着类似描述的被诅咒者不进行变化则是跟随村人胜利。）

![image](https://user-images.githubusercontent.com/44828559/50817950-80c9ae80-1360-11e9-8a5c-ca5b45f24a3c.png)

**Comment by Sunev** [comment]
由 404f2af0 修正
