### ISSUE TITLE
提议修改：替身君是模仿而来的指定连坐职业时，选择目标需要等待很久。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#65]
**简述bug**
请概要地描述一下bug的情况。
替身君是模仿而来的复仇者职业，在D1被咬死时，等待了45秒才开枪。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/72580

**出现bug的玩家昵称**
替身君

**出现bug的时间**
第二天天亮

**预期行为**
一般来说按照替身的处理速度应当是无等待开枪？如果怕瞬间信息太多的话延迟5秒开枪时可以的吧…

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
不知道和替身是模仿者有关？另外不知道狩猎者的判定是如何的。

**Comment by Sunev** [comment]
由 d4d4a95 达成此需求
