### ISSUE TITLE
二重身无法使用二重身的技能

### ISSUE THREAD

**Issue by Camiuuu** [Sunev/jinrou#67]
**简述bug**
二重身无法使用二重身的技能

**出现bug的房间地址**
https://www.werewolf.com.cn/room/73157

**出现bug的玩家昵称**
佑仓

**出现bug的时间**
第三天夜里及之后

**预期行为**
二重身在第三天夜里及之后可以使用二重技能

**截屏**
![Image text](https://i.loli.net/2019/02/01/5c53ae079f80e.png)

**更多内容**
二重身在使用二重身技能获得怪盗后，对魅惑的女狼使用怪盗技能窃取职业，同时用二重身的技能获得了巫女的职业，怪盗→魅惑的女狼职业被巫女替换。自此之后的夜晚二重身只能使用巫女的技能。

**Comment by YagamiMirai** [comment]
如此复杂的操作卡缪是怎么做出来的【腻害
