### ISSUE TITLE
人狼袭击被陷阱师守护对象&血腥玛丽诅咒对象时，人狼在第二天早上没有因陷阱而死

### ISSUE THREAD

**Issue by Camiuuu** [Sunev/jinrou#68]
**简述bug**
人狼袭击被陷阱师守护对象&血腥玛丽诅咒对象时，人狼在第二天早上没有因陷阱而死

**出现bug的房间地址**
https://www.werewolf.com.cn/room/73904

**出现bug的玩家昵称**
陷阱师「でびでび・でびる」、一匹狼「【喝茶联盟】ダンロボ」、圣痕者「Reno78」、血腥玛丽「松狮酱」

**出现bug的时间**
第五天的白天

**预期行为**
【喝茶联盟】ダンロボ 的死因是 陷阱。
【喝茶联盟】ダンロボ 不成样子的尸体被发现了。
Reno78 的死因是 玛丽的诅咒。
Reno78 不成样子的尸体被发现了。

**截屏**
无

**更多内容**
无

**Comment by YagamiMirai** [comment]
我觉得和https://github.com/Sunev/jinrou/issues/51 是同一个问题：
袭击的目标由于其他原因死亡，反杀的效果就不生效了
不知道算设定还是bug
