### ISSUE TITLE
使用“以相同设定建立新房间”时出现问题

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#70]
**简述bug**
请概要地描述一下bug的情况。
使用“以相同设定建立新房间”时，无法点击“展开游戏开始界面”
体现为点击后没有任何提示。
此外，此bug出现后，以普通方式建立新房间也无法展开开始界面了。

**出现bug的房间地址**
N/A

**出现bug的玩家昵称**
N/A

**出现bug的时间**
N/A

**预期行为**
正常展开开始界面

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
据称清理缓存可以暂时解决此问题。
似乎和浏览器无关？多个浏览器有此bug的报告（大部分为chrome核心）
另：我使用的360极速浏览器chrome核心，触发bug后无法使用鼠标手势功能（不知道有用没有就一起汇报了）

**Comment by Sunev** [comment]
由 51f37e6 修复
