### ISSUE TITLE
Endless下，夜间加入而清晨结算时，玩家加入失败。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#71]
**简述bug**
请概要地描述一下bug的情况。
夜间加入游戏，次日清晨死掉一个手动连坐职业，连坐后直接结算胜利，夜间加入的没有成功天降。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/74179

**出现bug的玩家昵称**
鱼家小店的偶像鱼儿大人

**出现bug的时间**
第3天的清晨。

**预期行为**
成功加入游戏

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
![image](https://user-images.githubusercontent.com/44828559/52990754-a7413600-3444-11e9-9f01-31145a85c3f8.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Gennadiyev** [comment]
”第三天的白天到来“后结算狩猎者类技能，玩家加入在此之后。可以理解，应该属于预期范围。

**Comment by YagamiMirai** [comment]
> ”第三天的白天到来“后结算狩猎者类技能，玩家加入在此之后。可以理解，应该属于预期范围。

我不认为如此，人狼袭击导致村人数等于人狼数而又转生/天降村人（或被反杀导致人狼数为0又转生人狼）导致不结进行胜负判定阶段甚至天降狐狸导致判定为妖狐胜利都是可以的，说明胜负判定阶段位于转生/天降阶段后。而狩猎者技能结算位于玩家加入前，并在此之后额外插入结算了一个胜负判定阶段应该是导致这个现象的原因。

至于这是个bug还是原本设定，就交给C大或者uyho桑来判定吧。
