### ISSUE TITLE
帮手帮助的玩家死亡时，帮手没有变为灵界配色。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#72]
**简述bug**
请概要地描述一下bug的情况。
作为帮手且被帮助的玩家死亡时，帮手依旧使用白天-夜晚的配色而非灵界的配色，但灵界发言是灵界配色的。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/74186
我是在这里发现的不过和房间无关啦

**出现bug的玩家昵称**
请于此处粘贴玩家昵称或ID。

**出现bug的时间**
被帮助的玩家死亡后

**预期行为**
变为灵界配色

**截屏**
在想截图的时候曼茶转生了我也没办法啊…

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 ab0b38d 修复
