### ISSUE TITLE
续：使用“以相同设定建立新房间”时，最大人数变成房间的总人数

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#74]
**简述bug**
请概要地描述一下bug的情况。
使用“以相同设定建立新房间”时，房间的默认最大人数会变成5人
虽然可以在新建房间时重新设置，但稍不注意就会开启最大人数为5人的房间
此外，此bug出现后，以普通方式建立新房间，默认的最大人数也变成5人了

**出现bug的房间地址**
N/A

**出现bug的玩家昵称**
N/A

**出现bug的时间**
N/A

**预期行为**
按照上个房间的最大人数继承，若新建则按目前的默认30人。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
可能是https://github.com/Sunev/jinrou/issues/70 的后续bug

**Comment by Sunev** [comment]
由 68365a2 修复
