### ISSUE TITLE
对 吴京 使用了死者复活术。手滑了一下，不小心复活了 吴京。

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#76]
**简述bug**
请概要地描述一下bug的情况。
例如：猫又决定复活的玩家和手滑提示的玩家是同一个人。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/74345

**出现bug的玩家昵称**
akioi、吴京

**出现bug的时间**
第三天夜里

**预期行为**
没有手滑提示

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by YagamiMirai** [comment]
推测：判定复活手滑后在当前所有死亡角色中随机选择，没有排除第一次选择的角色

**Comment by Sunev** [comment]
由 ea805eb 修复
