### ISSUE TITLE
人狼被怪盗盗取职业时，能够提前得知自己被盗取了

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#79]
**简述bug**
请概要地描述一下bug的情况。
人狼在夜间被怪盗盗取职业，天亮后狼单中没有自己但是有怪盗，所以可以提前得知自己被盗取了职业。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/76047

**出现bug的玩家昵称**
鱼家小店的偶像鱼儿大人
蒼崎青子

**出现bug的时间**
第一天夜里~第二天天亮

**预期行为**
在被提示“○○的职业被盗走了，变成了怪盗。”之前不知道自己不在名单中，也看不到怪盗的名字。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
![image](https://user-images.githubusercontent.com/44828559/53937918-88e86500-40e9-11e9-8bce-a94275ae76ce.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 30a5061 修复
