### ISSUE TITLE
按钮保留？

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#80]
**简述bug**
请概要地描述一下bug的情况。
使用配置Endless火锅时，自己是房主的情况下，如果自己没有加入游戏，则会保留开始游戏前的按钮。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/76244

**出现bug的玩家昵称**
Nyaplus111
（是账号，昵称我自己都懒得打了（））

**出现bug的时间**
开始游戏的瞬间

**预期行为**
只有加入游戏按钮

**截屏**
![default](https://user-images.githubusercontent.com/29174788/54030662-4c9b2e80-41e7-11e9-99d0-20a403cb1628.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by StarlightA** [comment]
这个bug好像存在过一段时间了（
另外和浏览器无关

**Comment by StarlightA** [comment]
刷新也解决不了

**Comment by StarlightA** [comment]
补充：点开按钮还可以正常编辑设定和踢人，只不过点完之后提示“游戏已经开始“

**Comment by Sunev** [comment]
由 ff4eac0 修复
