### ISSUE TITLE
观战者的自言自语

### ISSUE THREAD

**Issue by StarlightA** [Sunev/jinrou#81]
**简述bug**
Endless黑暗火锅模式下，白天进入犹豫时间后，已经加入游戏但尚处于观战者的发言方式变成自言自语

**出现bug的房间地址**
https://www.werewolf.com.cn/room/76520

**出现bug的玩家昵称**
小婚婚

**出现bug的时间**
第二天投票阶段

**预期行为**
颜色是旁观者的颜色，发言方式为向全员发言

**截屏**
![图片](https://user-images.githubusercontent.com/29174788/54082031-3bb6fe00-434a-11e9-8cd9-0606bb2c1d1d.png)

**更多内容**
其实这图片是婚婚的，我没下

**Comment by Sunev** [comment]
但是已经点了加入啊，不变成自言自语才奇怪吧。。
