### ISSUE TITLE
被诅咒者身上有圣职者的圣盾时被吸血鬼袭击，圣盾破掉并没有加入吸血鬼。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#82]
**简述bug**
请概要地描述一下bug的情况。
被诅咒者身上带有圣职者的圣盾，在夜间被吸血鬼袭击后提示“被神圣的力量守护了”，第二天投票入夜后没有变为吸血鬼。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/77076

**出现bug的玩家昵称**
路德 被诅咒者

**出现bug的时间**
D3夜

**预期行为**
圣盾仅在会导致死亡的时机消耗并阻止死亡。
被诅咒者被吸血鬼袭击应不消耗圣盾，并在第二天变为吸血鬼。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
圣盾阻止的是袭击，不仅仅是死亡

**Comment by YagamiMirai** [comment]
> 圣盾阻止的是袭击，不仅仅是死亡

**被神圣的力量守护的人只限免死的时候，被守护的人本人才会被告知“被神圣的力量守护了”这件事。**

那就是描述问题咯？

**Comment by Sunev** [comment]
你说得对，日文版没有这句话
这是翻译的时候加的
因为我想偷懒不做https://jinrou-doc.uhyohyo.net
所以塞了很多技术细节在职业简介里面。。。

**Comment by YagamiMirai** [comment]
讲真我一直以为圣盾只有在不破盾就会死的情况下才会破掉…
