### ISSUE TITLE
提议修改：endless的配置设定文本

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#84]
**简述bug**
请概要地描述一下bug的情况。
这个地方是不是把“立刻转生”改成“有可能转生”会好一些
以及感觉是不是少了个“的”字

**出现bug的房间地址**
N/A

**出现bug的玩家昵称**
N/A

**出现bug的时间**
配置房间时

**预期行为**
N/A

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。
![image](https://user-images.githubusercontent.com/44828559/54809227-a60e5d80-4cbd-11e9-9393-89d20b074759.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 a308a081237c157c8c2bab381e539168e973616d 改善翻译
