### ISSUE TITLE
炼成模式下，狂爱者×巫女使用巫女技能时抵抗追随恋人自尽时，提示信息刷屏且不会立刻死亡。

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#85]
**简述bug**
请概要地描述一下bug的情况。
在炼成模式下，狂爱者×巫女，开启了巫女技能，由于狂爱者的爱慕对象死亡而应当追随死亡时，在当天天亮的瞬间，灵界会出现大量的【〇〇〇 凭借神圣的力量抵抗了 追随恋人自尽。】

**出现bug的房间地址**
https://www.werewolf.com.cn/room/78586

**出现bug的玩家昵称**
压路机：狂爱者×巫女

**出现bug的时间**
第3天天亮

**预期行为**
巫女的技能无法抵抗追随自尽，或仅在天亮时提示一次，并在第二天投票后追随自尽。

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。
![image](https://user-images.githubusercontent.com/44828559/54877351-341e4b80-4e58-11e9-957f-2cd811a1d2b4.png)

**更多内容**
https://github.com/Sunev/jinrou/issues/61
可能是相关的bug？

**Comment by Sunev** [comment]
不相关，巫女就是当天内不计次数的抵抗死亡

**Comment by Sunev** [comment]
我看了一下代码，巫女是能够抵抗自杀的。
根据[日文文档](https://jinrou-doc.uhyohyo.net/jobs/priest)的描述，圣职者的守护也应当能够抵抗自杀，虽然实际上并不能够。可能是uhyo的实现不完善。已经向他提出。

此处计划先修正巫女的翻译，订正为“巫女能够抵抗自杀”

**Comment by Sunev** [comment]
关于重复的日志，这里是按照巫女预期只尝试自杀了100次，而没有陷入死循环。
我抽空会考虑一下怎样避免日志的重复输出。
