### ISSUE TITLE
（代百里守约提交）炼成模式下 假死的狡猾的狼取消假死后被处刑，次日会再次复活

### ISSUE THREAD

**Issue by YagamiMirai** [Sunev/jinrou#87]
**简述bug**
狡猾的狼N4假死，N5取消天亮复活，并在D5被处刑后，于D6天亮再次复活。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/81601

**出现bug的玩家昵称**
衣更真绪

**出现bug的时间**
D6天亮

**预期行为**
不应该复活第二次

**截屏**
如果能够提供有效的截屏，能够更好地协助我修复bug。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
由 6078a30 修复
