### ISSUE TITLE
巫女抵抗追随抵抗了了两天。

### ISSUE THREAD

**Issue by nanoiko** [Sunev/jinrou#88]
**简述bug**
巫女抵抗了两天。

**出现bug的房间地址**
https://www.werewolf.com.cn/room/81955。

**出现bug的玩家昵称**
姬宫桃李。

**出现bug的时间**
第一天夜里和第二天

**预期行为**
应该在第一天处刑结束后追随

**截屏**
![image](https://user-images.githubusercontent.com/11154659/56668826-c9746000-66e2-11e9-9d76-28940176a10d.png)
![image](https://user-images.githubusercontent.com/11154659/56668861-d6914f00-66e2-11e9-8608-f739cd4a5ad0.png)

。
将图片文件拖动至此处，或截图后按Ctrl+V即可。

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
与 #127 相同，已处置
