### ISSUE TITLE
简易黑暗火锅随机替换的职业不显示在公开职业里

### ISSUE THREAD

**Issue by chanssi** [Sunev/jinrou#89]
**简述bug**
简易黑暗火锅随机替换的职业不显示在公开职业里，会显示在希望役职里

**出现bug的房间地址**
#82026   #82027

**出现bug的玩家昵称**

**出现bug的时间**
游戏开始时的公布职业和希望役职阶段

**预期行为**
公开职业时显示特殊职业 或 希望役职同公开职业全部都不显示特殊职业

**截屏**
![5cc1eb4b8a4dc](https://user-images.githubusercontent.com/12387091/56856604-c43c3d00-6990-11e9-857a-2f641b850f83.jpg)
![5cc1eb4c28b8b](https://user-images.githubusercontent.com/12387091/56856605-c4d4d380-6990-11e9-87d5-0a9eba7a834f.jpg)

https://i.loli.net/2019/04/26/5cc1eb4b8a4dc.jpg
 https://i.loli.net/2019/04/26/5cc1eb4c28b8b.jpg
**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by chanssi** [comment]
*...公开职业时显示特殊职业
太困了错字见谅

**Comment by Sunev** [comment]
不要在意，发言的内容是可以修改的，虽然会留下修改历史。
