### ISSUE TITLE
猫又复活时，手滑了一下复活了当日死亡的目标，并且该目标没有出现死亡提示

### ISSUE THREAD

**Issue by nanoiko** [Sunev/jinrou#90]
**简述bug**
猫又复活时，手滑了一下复活了当日死亡的目标，并且改目标没有过出现死亡提示

**出现bug的房间地址**
https://www.werewolf.com.cn/room/82209

**出现bug的玩家昵称**
被复活：张新杰 猫又：安文逸

**出现bug的时间**
第二天夜里

**预期行为**

**截屏**
![image](https://user-images.githubusercontent.com/12387091/56856574-3c563300-6990-11e9-8c67-f1e54437feeb.png)
![image](https://user-images.githubusercontent.com/12387091/56856576-4a0bb880-6990-11e9-9ac8-2b2cd94c8553.png)

http://i1.bvimg.com/575651/060e39337cbdbeba.png
http://i1.bvimg.com/575651/97f8c7457fc3845a.png

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
请把截图直接贴上来。。你发的截图链接我打不开
截图→在输入框Ctrl+V即可

**Comment by Sunev** [comment]
与 https://github.com/uhyo/jinrou/issues/430 相同
