### ISSUE TITLE
人狼染病后因为狼之子死亡可以袭击两人

### ISSUE THREAD

**Issue by chanssi** [Sunev/jinrou#91]
**简述bug**
人狼染病后因为狼之子死亡可以袭击两人

**出现bug的房间地址**
https://www.werewolf.com.cn/room/82848

**出现bug的玩家昵称**
羽风薰

**出现bug的时间**
第四天夜里

**预期行为**
人狼因为染病不能袭击，即使狼子死亡也不能

**截屏**

![_~M44P3PZ1~9J`SP}LQ}0GT](https://user-images.githubusercontent.com/42495064/57178215-c7a75b00-6e9f-11e9-81fd-cd0481636fe4.png)

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
![tempFileForShare_20190504-200434](https://user-images.githubusercontent.com/12387091/57179538-8ddf5000-6eb1-11e9-98dd-3ffe236a9279.jpg)
https://jinrou-doc.uhyohyo.net/jobs/wolfcub
根据uhyo的文档，目前这个情况不视为bug
