### ISSUE TITLE
阎魔视角里因炸弹而死的玩家显示因落入陷阱死亡

### ISSUE THREAD

**Issue by chanssi** [Sunev/jinrou#93]
**简述bug**
阎魔视角里因炸弹而死的玩家显示因落入陷阱死亡
*被处决的携带炸弹的玩家职业是陷阱师×炸弹魔

**出现bug的房间地址**
https://www.werewolf.com.cn/room/83173

**出现bug的玩家昵称**
鬼龙红郎

**出现bug的时间**
D2投票处决时

**预期行为**
阎魔视角因炸弹而死

**截屏**
![X2 `)T)5$%( RN$H$G)TK}5](https://user-images.githubusercontent.com/42495064/57527783-261e7e80-7363-11e9-8c31-bcaec2462ecc.png)

**Comment by Sunev** [comment]
与 #56 相同

**Comment by Sunev** [comment]
由 42254b8900a20ba0da1d6913b2cf1af20d539b51 补充职业描述
