### ISSUE TITLE
炼成模式下狼x吸血鬼用吸血鬼袭击了陷阱自守的狼队友，判断狼队友触发陷阱，狼x吸血鬼存活

### ISSUE THREAD

**Issue by nanoiko** [Sunev/jinrou#95]
**简述bug**
炼成模式下狼x吸血鬼用吸血鬼袭击了陷阱自守的狼队友，判断狼队友触发陷阱，狼x吸血鬼存活

**出现bug的房间地址**
https://www.werewolf.com.cn/room/83726

**出现bug的玩家昵称**
狼x吸血鬼：鸣上岚
狼x陷阱：濑名泉

**出现bug的时间**
第四天夜里

**预期行为**
狼x陷阱存活，狼x吸血鬼触发陷阱

**截屏**
<img src='http://i1.bvimg.com/575651/03151b83c265b875.png'>

**更多内容**
如果有更多能够协助修复bug的内容，请填写在这里。

**Comment by Sunev** [comment]
已修复
