### ISSUE TITLE
猫又手滑复活了当天离开村子的间谍，并且没有离开村子的提示

### ISSUE THREAD

**Issue by nanoiko** [Sunev/jinrou#96]
**简述bug**
猫又手滑复活了当天离开村子的间谍，并且没有离开村子的提示

**出现bug的房间地址**
https://www.werewolf.com.cn/room/84325

**出现bug的玩家昵称**
猫又 高峯翠
间谍 天祥院英智

**出现bug的时间**
第二天夜里

**预期行为**
出现离开村子的提示

**截
<img src='http://i1.bvimg.com/575651/807a55be683b21cb.png'>

**更多内容**
你上次明明说已经修复了（…）

**Comment by Sunev** [comment]
修复了，但是服务器还没更新呀
